# Generated by Django 6.0.7 on 2026-09-19 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('total_score', models.IntegerField(default=0)),
                ('avg_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('interview_duration', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('confidence_tips', models.TextField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('confidence_tips', models.TextField(blank=True, null=True)),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.interview')),
            ],
            options={
                'db_table': 'interview_responses',
                'ordering': ['question_number'],
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['is_completed'], name='interviews_is_comp_fa325e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewresponse',
            index=models.Index(fields=['interview'], name='interview_r_intervi_c927e1_idx'),
        ),
    ]
